version: '1.0'
name: pipeline-20220521
displayName: pipeline-20220521
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-25932eb5
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@php
        name: build_php
        displayName: PHP 构建
        phpVersion: '8.0'
        commands:
          - php --version
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
permissions:
  - role: admin
    members: []
